#!/usr/bin/env python
# coding: utf-8

# In[ ]:


cities = ['Von ', 
          ', Paris', 
          ', Brüssel',
          ', London',
          ', Madrid',
          ', Peking',
          ', Washington',
          ', Berlin',
          ', Wien',
          ', Moskau',
          ', New York',
          ', Los Angeles',
          ', Tokio',
          ', Singapur',
          ', Düsseldorf',
          ', São Paulo',
          ', Mainz',
          ', München',
          ', Warschau',
          ', Stuttgart',
          ', Hannover',
          ', Tel Aviv',
          ', Kapstadt',
          ', Hamburg',
          ', Melbourne',
          ', Zhangjiakou',
          ', Manchester',
          ', Rom',
          ', Bratislava',
          ', Wiesbaden',
          ', Beirut',
          ', Zürich',
          ', Sedona',
          ', Köln',
          ', Schanghai',
          ', Dortmund',
          ', Mönchengladbach',
          ', Darmstadt',
          ', Ankara',
          ', Hanau',
          ', Frankfurt',
          ', Wolfsburg',
          ', Davos',
          ', Helsinki',
          ', Karlsruhe',
          ', Hongkong',
          ', Sakhir',
          ', Turin',
          ', Manila',
          ', Genf',
          ', Sinsheim',
          ', Offenbach',
          ', Sevilla',
          ', Jerusalem',
          ', Bielefeld',
          ', Gelsenkirchen',
          ', Taipeh',
          ', Gelsenkirchen',
          ', Leverkusen',
          ', Kiew',
          ', Chișinău',
          ', Mailand',
          ', Augusta',
          ', Budapest',
          ', Islamabad',
          ', Istanbul',
          ', Miami Gardens',
          ', Barcelona',
          ', Bischofshofen',
          ', Eltville',
          ', Lemberg',
          ', Rüdesheim',
          ', Saarbrücken',
          ', Vilnius',
          ', Bangkok',
          ', Freiburg',
          ', Bochum',
          ', Winsen',
          ', Bogotá',
          ', Yanqing',
          ', Innsbruck',
          ', Belgrad',
          ', Herzogenaurach',
          ', Weissenhaus',
          ', Monte Carlo',
          ', Kiel',
          ', Bonn',
          ', Colombo',
          ', Riesa',
          ', Garmisch-Partenkirchen',
          ', Buffalo',
          ', Venedig',
          ', Balve',
          ', Königswinter',
          ', Baku',
          ', Monaco',
          ', Doha',
          ', Bad Homburg',
          ', Tampere',
          ', Ratingen',
          ', Pliezhausen',
          ', Broken Hill',
          ', Königstein',
          ', Institut für Demoskopie Allensbach',
          ', Luxemburg ',
          ', Basel',
          ', Montreal',
          ', Odessa',
          ', Fürth',
          ', Wetzlar',
          ', Landshut',
          ', Lille',
          ', Dresden',
          ', Lissabon',
          ', Magdeburg',
          ', Straßburg',
          ', Mayen',
          ', Tiflis',
          ', Schwerin',
          ', Gießen',
          ', Amsterdam',
          ', Przemysl',
          ', Seoul',
          ', Neu-Isenburg',
          ', Neu Delhi',
          ', Saporischschja',
          ', Indian Wells',
          ', Hohen Neuendorf',
          ', Málaga',
          ', Koblenz',
          ', Marie-Curie-Gymnasium',
          ', Tripoli',
          ', Heidenrod',
          ', Megina-Gymnasium',
          ', Veldhoven',
          ', /Kiew',
          ', Dragobrat',
          ', Altenahr',
          ', Institut für und Demoskopie Allensbach'
          ', Wuppertal',
          ', Gárgoles de Abajo',
          ', Nowoluhanske',
          ', Bad Münstereifel',
          ', Skopje/Sofia/Belgrad',
          ', Erbil/Suleimaniyya',
          ', Lüdenscheid',
          ', Landgraf-Ludwigs-Gymnasium',
          ', Mörfelden-Walldorf',
          ', Jerewan',
          ', Großwallstadt',
          ', Pforzheim',
          ', Kabul',
          ', Friedberg',
          ', Bremen',
          ', Wetzikon',
          ', Mohács/Ráckeve',
          ', Stiring-Wendel/Forbach',
          ', Dhaka',
          '/Kiew',
          '/Oberursel',
          ', Nazaré',
          ', Dnipro',
          ', Eich',
          ', Shijingshan',
          ', Mariupol',
          ', Naha',
          ', Jounieh',
          ', Almaty',
          ', Reyhanli',
          ', Dublin',
          ', Mülheim an der Ruhr',
          ', Sydney',
          ', Mykolajiw',
          ', Sydney/Lismore',
          ',Kantonsschule Kreuzlingen',
          ', Palermo',
          ', Aarbergen-Michelbach',
          ', Marburg',
          ', Chişinău',
          ', Apartadó',
          ', Oberursel',
          ', Palma de Mallorca',
          ', Unterhaching',
          ', Salzburg',
          ', Augsburg',
          ', Zhangijiakou',
          ', Dachsenhausen',
          ', Parler Gymnasium, Schwäbisch Gmünd',
          ', Friedrich-List-Gymnasium, Asperg',
          ', Burghausen',
          ', Dietrich-Bonhoeffer-Gymnasium, Eppelheim',
          ', Galabov-Gymnasium, Sofia',
          ',  Chișinău',
          ', Dakar',
          ', Oldenburg',
          ', Eisenach',
          ', Friedrich-List-Schule',
          ', Kassel',
          ', Kirchzell',
          ', Pristina',
          ', Butzbach',
          ', Niedernhausen',
          ', Lahr',
          ', Salo',
          ', Aachen',
          ', Aventinus-Gymnasium',
          ', Wismar',
          ', Rimbach-Mitlechtern',
          ', Jakarta',
          ', Verona',
          ', Weilrod',
          ', Max-Planck-Gymnasium',
          ', Bologna',
          ', Urueña',
          ', Hasselroth',
          ', Bronnbach',
          ', Florenz',
          ', Kaiserslautern',
          ', Eschborn',
          ', Gotha',
          ', Usingen',
          ', Tannenbusch-Gymnasium',
          ', al-Ula',
          ', Sliač',
          ', Reinheim',
          ', Eppstein',
          ', Karolinen-Gymnasium, Rosenheim',
          ', Eindhoven',
          ', Bad Vilbel',
          ', Kantonsschule Kreuzlingen',
          ', Würzburg',
          ', Lahntal-Gosfelden',
          ', Gymnasium Ohmoor',
          ', Grävenwiesbach',
          ', Niamey',
          ', Hessenthal',
          ', Karl-Theodor-von-Dalberg-Gymnasium, Aschaffenburg',
          ', Korczowa',
          ', Idstein',
          ', St.-Anna-Schule',
          ', Austin',
          ', Hofheim',
          ',  São Paulo',
          ', Prag',
          ', Heidelberg',
          ', Deutsche Schule zu Porto',
          ', Dumersheim, Wilhelm-Hausenstein-Gymnasium',
          ', Kantonschule Uetikon am See',
          ', Bethlehem',
          ', Wilhelm-Hausenstein-Gymnasium, Dumersheim',
          ', Droste-Hülshoff-Gymnasium',
          ', Heinrich-Heine-Gymnasium',
          ', Kantonsschule Trogen',
          ' Karolinen-Gymnasium, Rosenheim',
          ', Rabanus-Maurus-Gymnasium',
          ', Gymnasium im Alfred-Grosser-Schulzentrum, Bad Bergzabern',
          ', Droste-Hülshoff-Gymnasium',
          ', Evangelisches Heidehofgymnasium',
          ', Kantonsschule Zürcher Oberland',
          ', Johann-Philipp-von-Schönborn-Gymnasium, Münnerstadt',
          ', Katholische Schule Liebfrauen',
          ', Leipzig',
          ', Hochtaunuskreis',
          ', Ras at-Tin',
          ', Ulm',
          ', Sofia',
          ', El Ejido',
          ', Douai',
          ', Vannes',
          ', Riga',
          ', Schleswig/Kiel',
          ', Irpin',
          ', Oestrich-Winkel',
          ', Santiniketan',
          ',  Megina-Gymnasium',
          ', Karasjok',
          ', Münnerstadt, Johann-Philipp-von-Schönborn-Gymnasium',
          ',   Gymnasium Fran Galović, Koprivnica',
          ', Bad Hombuirg',
          ', Fischbachtal',
          ', Rosenstein-Gymnasium, Heubach',
          ', Franziskanergymnasium Kreuzburg, Großkrotzenburg',
          ',  Lycée des Bourdonnières in Nantes',
          ', Gymnasium Kenzingen',
          ', Manon Retière',
          ', Münster',
          ', Meriem Renou-Marzorati',
          ', Mafalda Rakoš',
          ', Triberg',
          ', Hattersheim',
          ', Schladming',
          ', Griesheim',
          ', Dreieich',
          ', Gampaha',
          ', Pomigliano d’Arco',
          ', Neuenstadt am Kocher',
          ', Lappeenranta',
          ', Pinneberg',
          ', Prishtina',
          ', Aßlar',
          ', Gaziantep',
          ', Urla',
          ', Bad Saarow',
          ', Marseille',
          ', Ilbenstadt',
          ', Ramstein',
          ', Oberstufengymnasium Eschwege',
          ', Eppan',
          ', Wetterau',
          ', Vendôme']

